// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5KeVXsRQ1H-lvHNlxDCLA2uzY4eVPh0I',
    appId: '1:571676731513:web:69eebe9f8f74a6da6a0ca8',
    messagingSenderId: '571676731513',
    projectId: 'growkart-63712',
    authDomain: 'growkart-63712.firebaseapp.com',
    storageBucket: 'growkart-63712.firebasestorage.app',
    measurementId: 'G-F9RYDXD7CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGt9MKQHwTU9p_q7SthIdO9bTz8XW7Pwk',
    appId: '1:571676731513:android:e4bd6f4563b8c1046a0ca8',
    messagingSenderId: '571676731513',
    projectId: 'growkart-63712',
    storageBucket: 'growkart-63712.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_hpw6UZxrtehafHftUrnywfv8BizoBlY',
    appId: '1:571676731513:ios:d05a0172e03ce1396a0ca8',
    messagingSenderId: '571676731513',
    projectId: 'growkart-63712',
    storageBucket: 'growkart-63712.firebasestorage.app',
    iosBundleId: 'com.example.growkart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_hpw6UZxrtehafHftUrnywfv8BizoBlY',
    appId: '1:571676731513:ios:d05a0172e03ce1396a0ca8',
    messagingSenderId: '571676731513',
    projectId: 'growkart-63712',
    storageBucket: 'growkart-63712.firebasestorage.app',
    iosBundleId: 'com.example.growkart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5KeVXsRQ1H-lvHNlxDCLA2uzY4eVPh0I',
    appId: '1:571676731513:web:540f8a2e5ed93a796a0ca8',
    messagingSenderId: '571676731513',
    projectId: 'growkart-63712',
    authDomain: 'growkart-63712.firebaseapp.com',
    storageBucket: 'growkart-63712.firebasestorage.app',
    measurementId: 'G-GQQ843BMG8',
  );
}